//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Cv_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProjelerim
    {
        public int ID { get; set; }
        public string Proje_Adi { get; set; }
        public string Kullanilan_Diller { get; set; }
        public string ProjeLink { get; set; }
    }
}
